version: '3'
services:
  web:
    build: .
    environment:
      DB_HOST: "db"
      PORT: "80"
    ports:
      - "80:80"
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - './seed.sql:/docker-entrypoint-initdb.d/seed.sql'
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8080:80"